### ISSUE TITLE
View Action Cover Page using deep linked URL

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#284] opened 2022-02-04 12:43 UTC
It should be possible to navigate to an Action cover page using a deep linked URL:

```yaml
/actions/{action_id}
```

This should display the action cover page for the action with id `action_id`

Desktop:
https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2Fp0yd3uxnoPvpkZXKrbhR0O%2FNavigator%3Fpage-id%3D8%253A63%26node-id%3D381%253A11978%26viewport%3D241%252C48%252C0.5%26scaling%3Dscale-down%26starting-point-node-id%3D35%253A2546

Mobile:
https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2Fp0yd3uxnoPvpkZXKrbhR0O%2FNavigator%3Fpage-id%3D279%253A2669%26node-id%3D439%253A8791%26viewport%3D241%252C48%252C0.65%26scaling%3Dscale-down-width%26starting-point-node-id%3D279%253A5267

**Comment by chrisaballard** [comment] 2022-02-14 12:54
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/284?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by kdutia** [comment] 2022-02-15 11:58
closing as duplicate of #285

**Closed by kdutia** 2022-02-15 11:58 UTC
